site_name: AGNBoost
site_description: A machine learning toolkit for astronomical data analysis using XGBoost
site_author: Kurt Hamblin
site_url: https://kurthamblin.github.io/agnboost/

# Repository
repo_name: kurthamblin/agnboost
repo_url: https://github.com/kurthamblin/agnboost
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: getting-started.md
  - Tutorials:
    - Basic Usage: tutorials/basic-usage.md
    - Band Configuration: tutorials/band-configuration.md
    - Training from Scratch: tutorials/training-from-scratch.md
  - API Reference:
    - Catalog: api/catalog.md
    - AGNBoost: api/agnboost.md
    - Utilities: api/utils.md
  - About:
    - License: license.md