site_name: AGNBoost
site_description: A machine learning toolkit for astronomical data analysis using XGBoost
site_author: Kurt Hamblin
site_url: https://hamblin-ku.github.io/AGNBoost/

# Repository
repo_url: https://github.com/hamblin-ku/AGNBoost
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
    - content.action.view

# Plugins
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            show_root_heading: true
            show_root_toc_entry: false
            heading_level: 2
            members_order: source
            show_signature_annotations: true
            separate_signature: true
            show_bases: true
            show_inheritance_diagram: false
  - mkdocs-jupyter:
      execute: false
      allow_errors: false

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Updated navigation - single API page
nav:
  - Home: index.md
  - Tutorials:
    - Basic Usage: tutorials/basic-usage.ipynb
    - Custom Features and Transformed Targets: tutorials/CustomFeatures+Targets.ipynb
    - Band Configuration: tutorials/custom_bands.ipynb
    - Training from Scratch: tutorials/tuning+training.ipynb
  - API Reference: api.md

# Watch
watch:
  - agnboost/