name: Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
          # Install documentation dependencies
          pip install mkdocs-material
          pip install mkdocstrings[python]
          pip install mkdocs-jupyter
          
          # Install core scientific dependencies for imports
          pip install numpy pandas scikit-learn matplotlib scipy tqdm
          
          # Install optional dependencies, don't fail if unavailable
          pip install xgboost || echo "Warning: xgboost not available"
          pip install xgboostlss || echo "Warning: xgboostlss not available"
          pip install astropy || echo "Warning: astropy not available"

      - name: Install AGNBoost package
        run: |
          pip install -e . || echo "Package install failed, continuing with docs build"

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Deploy documentation
        run: mkdocs gh-deploy --force